#!/bin/bash
#SBATCH --nodes=1
#SBATCH --partition=rome
#SBATCH --ntasks-per-node=1
#SBATCH --time=1:00:00
#SBATCH --exclusive


PROJECT_SPACE=

if [ -z "$PROJECT_SPACE" ]; then
  echo "Error: PROJECT_SPACE is not set. Please set the project space path in this script. Example: export PROJECT_SPACE=/projects/0/prjsXXXX"
  exit 1
fi

CONTAINER=$PROJECT_SPACE/containers/megatron-torch-2.7-nvcr.25-04.sif
BIND_PATH=$PROJECT_SPACE

apptainer shell -B $BIND_PATH $CONTAINER

python download_data.py